### ISSUE TITLE
廃止されたAPIを使っていいんですか？これで日本が良くなると思っているんですか？

### ISSUE THREAD

**Issue by ch4rindo** [SpaceServerUniverse/UniverseCoreV2#33]
![image](https://github.com/user-attachments/assets/24758511-22bb-476a-8ca4-4a980dc26297)

https://yumenavi.info/vue/lecture.html?gnkcd=g012915

**Comment by m1sk9** [comment]
日本の政治体制が悪いのは若者が非推奨APIを使ってるからである‼️若者は非推奨APIを使うな‼️

ちなみに代替え先はわかりません

**Comment by yuyaprgrm** [comment]
https://jd.papermc.io/paper/1.21.1/org/bukkit/inventory/ItemStack.html#%3Cinit%3E(org.bukkit.Material)によれば
```java
ItemStack.of(Material.DIAMOND_SWORD)
```
を使用するべきであるとのこと

**Comment by m1sk9** [comment]
> https://jd.papermc.io/paper/1.21.1/org/bukkit/inventory/ItemStack.html#%3Cinit%3E(org.bukkit.Material)によれば
> 
> ```java
> 
> ItemStack.of(Material.DIAMOND_SWORD)
> 
> ```
> 
> を使用するべきであるとのこと

@yuyaprgrm @ch4rindo 

よかった‼️これで日本は安泰だ‼️

**Comment by m1sk9** [comment]
誰でも良いのでぜひコントリビュートください
