### ISSUE TITLE
ライセンス違反を解消する

### ISSUE THREAD

**Issue by m1sk9** [SpaceServerUniverse/UniverseCoreV2#38]
Minecraft Java Edition におけるサーバーソフトウェアの始祖である Bukkit は [The GNU General Public License v3.0](https://www.gnu.org/licenses/gpl-3.0.en.html) を継承しているため Bukkit を Fork している Spigot , Paper は GPL の汚染を受けます

UniverseCoreV2 は Paper API を依存関係に持ったまま OSS として公開しているため MIT LICENSE のままだとライセンス違反となっているため GPL に置き換える

詳しくは [ライセンス感染](https://ja.wikipedia.org/wiki/%E3%83%A9%E3%82%A4%E3%82%BB%E3%83%B3%E3%82%B9%E6%84%9F%E6%9F%93)

**Comment by OneWalkDev** [comment]
GPL3に変えてプルリク送っといて

**Comment by m1sk9** [comment]
どね
