### ISSUE TITLE
@paramと@returnの説明に型を含むべきか？

### ISSUE THREAD

**Issue by PJZ9n** [SpaceServerUniverse/UniverseCoreV2#62]
Javadocコメントの `@param` と `@return` には説明文を記載できますが、ここに型を記載するかについて。
既存のコードを軽く確認した限りでは、概ね説明文の先頭に型を記載しているように思うのでそれで良いとは思います。
ただ、Javadocの仕様 [@param](https://docs.oracle.com/javase/7/docs/technotes/tools/windows/javadoc.html#param) [@return](https://docs.oracle.com/javase/7/docs/technotes/tools/windows/javadoc.html#return) で強制されているわけではなく、[慣例のようです](https://www.oracle.com/technical-resources/articles/java/javadoc-tool.html#@param)。

> By convention, the first noun in the description is the data type of the parameter.

Googleによる日本語訳
> 慣例により、説明の最初の名詞はパラメータのデータ型です。

そのため、これを明文化しておく必要があると考えています。

- 含む場合の例
```java
/**
 * @param user User 対象ユーザーのインスタンス
 * @return Money 作成されたMoneyインスタンス
 */
public Money createMoney(User user) {
  //...
}
```

- 含まない場合の例
```java
/**
 * @param user 対象ユーザーのインスタンス
 * @return 作成されたMoneyインスタンス
 */
public Money createMoney(User user) {
  //...
}
```

**Comment by m1sk9** [comment]
個人的意見としてこのプロジェクトはそこまで JavaDoc の恩恵を受けていない + 設計及び処理内容は比較的簡潔になっているためそこまで厳格にコーディングスタイルを決めなくてもいいかなぁ (というかコメントがなかったり不正な関数が大量に残ってて現状の `main` ブランチでは JavaDoc の生成ができないのでそれを直してからの話になると思っています)
