### ISSUE TITLE
メソッドシグネチャの情報と同一のJavadocタグを記載すべきか？

### ISSUE THREAD

**Issue by PJZ9n** [SpaceServerUniverse/UniverseCoreV2#63]
# 要約
```java
/**
 * @param user User
 * @return Money
 */
public Money createMoney(User user) {
  //...
}
```
上記のように、メソッドの定義行(シグネチャ)に含まれている情報だけを含んだJavadocコメントタグ(`@param`, `@return`)を記載すべきか？

# 内容
メソッドのシグネチャに含まれるのとまったく同じ情報をJavadoc形式のコメントで再度記述する必要があるかどうかについて。

現状、このようなコメントの有無がコードによって不統一になっています。

個人的には、シグネチャ自体が機械判読可能であることから(ほぼ)完全に代替可能であること、シグネチャを変更した際すべての場合で必ずコメントも同時に編集することになり、単純なタイプ量増加とそれによるミスの増加が起きる可能性があるため、それらの情報を冗長に記載する必要はないと考えています。(シグネチャで表現しきれない追加情報がある場合は除く)

<details>
<summary>追加情報がある場合の例</summary>

```java
/**
 * ユーザーに基づきお金を作成します。
 */
public Money createMoney(User user) {
  //...
}
```

```java
/**
 * @param user User 対象ユーザーのインスタンス
 * @return Money 作成されたMoneyインスタンス
 */
public Money createMoney(User user) {
  //...
}
```
※descriptionの最初に型を入れるかどうかについてはこの問題では触れていません。(これは仕様ではない)
</details>

一方で、超大規模プロジェクトであるOracle の Java Software で作成された Java プログラムのドキュメント コメントで使用する[スタイル ガイド (Required Tags)](https://www.oracle.com/jp/technical-resources/articles/java/javadoc-tool.html#requiredtags)では、いくつかの理由から`@params`と`@return`はすべてのパラメータ・メソッドで必須となっています。

どちらにせよ、コーディングスタイルを明文化することによってコードを書く、読む、レビューするときはもちろん、例えばCIでそれらをチェックするようになったときにも役に立ちます。(該当する全てのコードをすぐに書き換えたり、急に全員が完璧にするのは難しいかもしれませんが、明文化することだけでもメリットはあると思います)
ちゃんと決めるのは大変なので、有名どころの実績のあるスタイルガイドに準拠するというのもありですね。

**Comment by m1sk9** [comment]
https://github.com/SpaceServerUniverse/UniverseCoreV2/issues/62#issuecomment-2357924008
